services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:${CP_VERSION}
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:${CP_VERSION}
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
  kafka-init:
    container_name: kafka-init
    image: confluentinc/cp-kafka:${CP_VERSION}
    depends_on:
      - kafka
    volumes:
      - ./provisioning/kafka-init:/tmp/kafka-init
    command: '/tmp/kafka-init/create-topics'
  schema-registry:
    container_name: schema-registry
    image: confluentinc/cp-schema-registry:${CP_VERSION}
    depends_on:
      - kafka
    ports:
      - '8081:8081'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:29092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
  kafka-rest:
    container_name: kafka-rest
    image: confluentinc/cp-kafka-rest:${CP_VERSION}
    depends_on:
      - kafka
      - schema-registry
    ports:
      - '8082:8082'
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KAFKA_REST_ZOOKEEPER_CONNECT: zookeeper:2181
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:${UI_VERSION}
    ports:
      - '8080:8080'
    depends_on:
      - kafka
      - schema-registry
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
    volumes:
      - ./provisioning/kafka-ui/config.yaml:/etc/kafkaui/dynamic_config.yaml
