#!/usr/bin/env bash

function create_topic {
    kafka-topics \
        --create \
        --if-not-exists \
        --zookeeper zookeeper:2181 \
        --partitions $1 \
        --replication-factor 1 \
        --topic $2
}

cub kafka-ready -b kafka:29092 1 20 &&
    create_topic 4 avro.pedantic-shamir
