#!/usr/bin/env bash

cat key.avsc value.avsc value.json |
    jq \
        --slurp \
        --compact-output \
        '{key_schema: .[0]|@json, value_schema: .[1]|@json, records: [{key: .[2].id, value: .[2]}]}' |
    curl \
        --request POST \
        --header 'Content-Type: application/vnd.kafka.avro.v2+json' \
        --header 'Accept: application/vnd.kafka.v2+json' \
        --data-binary @- \
        http://localhost:8082/topics/avro.pedantic-shamir
